// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqlDPPXi-M9-oIW36pCM-K8q9Nl9uvNQM',
    appId: '1:906528366453:web:cbd461d6efcdf9fc56fd3c',
    messagingSenderId: '906528366453',
    projectId: 'arah-app-11744',
    authDomain: 'arah-app-11744.firebaseapp.com',
    storageBucket: 'arah-app-11744.appspot.com',
    measurementId: 'G-S5G3WF0H7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeKgoe7eFqIzGGhMiCu37hKRy5aNvmpl8',
    appId: '1:906528366453:android:dcaa1d6eedd2e87e56fd3c',
    messagingSenderId: '906528366453',
    projectId: 'arah-app-11744',
    storageBucket: 'arah-app-11744.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbkTD2JRpsE4uc5SU55YdVhoBGOi14oE',
    appId: '1:906528366453:ios:0a6b1ad35971088456fd3c',
    messagingSenderId: '906528366453',
    projectId: 'arah-app-11744',
    storageBucket: 'arah-app-11744.appspot.com',
    iosBundleId: 'com.example.arahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHbkTD2JRpsE4uc5SU55YdVhoBGOi14oE',
    appId: '1:906528366453:ios:0a6b1ad35971088456fd3c',
    messagingSenderId: '906528366453',
    projectId: 'arah-app-11744',
    storageBucket: 'arah-app-11744.appspot.com',
    iosBundleId: 'com.example.arahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqlDPPXi-M9-oIW36pCM-K8q9Nl9uvNQM',
    appId: '1:906528366453:web:3400be3d0c3d7d2556fd3c',
    messagingSenderId: '906528366453',
    projectId: 'arah-app-11744',
    authDomain: 'arah-app-11744.firebaseapp.com',
    storageBucket: 'arah-app-11744.appspot.com',
    measurementId: 'G-Z16H83ND4Q',
  );
}
